-- Código com os esquemas do banco
SET TIMEZONE TO 'GMT+3'; -- São Paulo timezone
SET DATESTYLE TO 'DMY';

CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
    CPF VARCHAR(11) PRIMARY KEY,
    TELEFONE VARCHAR(11) NOT NULL,
    CARGO VARCHAR(30) NOT NULL CHECK(UPPER(CARGO) IN ('ADMIN', 'PROF')),
    NOME VARCHAR(30) NOT NULL,
    DATA_NASC DATE,
    SEXO VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS ADMINISTRADOR (
    CPF VARCHAR(11) PRIMARY KEY,
    CONSTRAINT FK_ADM FOREIGN KEY (CPF) REFERENCES FUNCIONARIOS(CPF) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS PROFESSOR (
    FUNCIONARIO VARCHAR(11) PRIMARY KEY,
    CFEP VARCHAR(12) NOT NULL,
    QNTD_TURMAS INTEGER,
    CONSTRAINT FK_PROF FOREIGN KEY (FUNCIONARIO) REFERENCES FUNCIONARIOS(CPF) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS IDIOMAS_PROF (
    PROFESSOR VARCHAR(11) NOT NULL,
    IDIOMA VARCHAR(20) NOT NULL,
    CONSTRAINT PK_IDIOMAS_PROF PRIMARY KEY (PROFESSOR, IDIOMA),
    CONSTRAINT FK_IDIOMAS_PROF FOREIGN KEY (PROFESSOR) REFERENCES PROFESSOR(FUNCIONARIO) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS PATROCINADOR (
    CNPJ VARCHAR(14) PRIMARY KEY,
    NOME_EMPRESA VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS CONTATO (
    ADMINISTRADOR VARCHAR(11) NOT NULL,
    EMPRESA VARCHAR(14) NOT NULL,
    "DATA" DATE NOT NULL, -- Só salva a data do último contato com a empresa
    CONSTRAINT PK_CONTATO PRIMARY KEY (ADMINISTRADOR, EMPRESA),
    CONSTRAINT FK_ADM FOREIGN KEY (ADMINISTRADOR) REFERENCES ADMINISTRADOR(CPF) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_EMP FOREIGN KEY (EMPRESA) REFERENCES PATROCINADOR(CNPJ) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS REPRESENTANTES (
    EMPRESA VARCHAR(14) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    TELEFONE VARCHAR(50) NOT NULL,
    CONSTRAINT PK_REP PRIMARY KEY (EMPRESA, NOME, TELEFONE),
    CONSTRAINT FK_EMP FOREIGN KEY (EMPRESA) REFERENCES PATROCINADOR(CNPJ) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS ALDEIA (
    "LOCAL" VARCHAR(25) PRIMARY KEY, -- String com a geolocalização de uma aldeia, por exemplo (-22.013333, -47.888758)
    IDIOMA_OFICIAL VARCHAR(30) NOT NULL,
    NUM_MORADORES INTEGER,
    ETNIA VARCHAR(15)
);

CREATE TABLE IF NOT EXISTS INDIGENA (
    CPF VARCHAR(11) PRIMARY KEY,
    DATA_NASC DATE,
    RANI VARCHAR(15) NOT NULL,
    NOME VARCHAR(50),
    SEXO VARCHAR(20),
    ALDEIA VARCHAR(25) NOT NULL,
    CONSTRAINT FK_INDIGENA FOREIGN KEY (ALDEIA) REFERENCES ALDEIA("LOCAL") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS IDIOMAS_INDIGENA (
    INDIGENA VARCHAR(11) NOT NULL,
    IDIOMA VARCHAR(20) NOT NULL,
    CONSTRAINT PK_IDIOMAS_IND PRIMARY KEY (INDIGENA, IDIOMA),
    CONSTRAINT FK_IDIOMAS_IND FOREIGN KEY (INDIGENA) REFERENCES INDIGENA(CPF) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS PATROCINIO (
    NOTA_FISCAL VARCHAR(6) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS FORNECIMENTO (
    PATROCINIO VARCHAR(6) PRIMARY KEY,
    "DATA" DATE NOT NULL,
    PATROCINADOR VARCHAR(14) NOT NULL,
    TIPO VARCHAR(20) NOT NULL CHECK(UPPER(TIPO) IN ('PROJETO', 'CURSO')),
    CONSTRAINT UNIQUE_SK_FORNECIMENTO UNIQUE("DATA", PATROCINADOR),
    CONSTRAINT FK_PK_FORNECIMENTO FOREIGN KEY (PATROCINIO) REFERENCES PATROCINIO(NOTA_FISCAL) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_PATROCINADOR_FORN FOREIGN KEY (PATROCINADOR) REFERENCES PATROCINADOR(CNPJ) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS MATERIAL (
    IMEI VARCHAR(15) PRIMARY KEY,
    TIPO VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS MATERIAL_FORNECIMENTO (
    FORNECIMENTO VARCHAR(6) NOT NULL,
    MATERIAL VARCHAR(15) NOT NULL,
    QUANTIDADE INTEGER NOT NULL,
    CONSTRAINT PK_MATERIAL_FORNECIMENTO PRIMARY KEY(FORNECIMENTO, MATERIAL),
    CONSTRAINT FK_FORNECIMENTO_MF FOREIGN KEY (FORNECIMENTO) REFERENCES FORNECIMENTO(PATROCINIO) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_MATERIAL_MF FOREIGN KEY (MATERIAL) REFERENCES MATERIAL(IMEI) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS CURSO (
    CODIGO VARCHAR(10) PRIMARY KEY,
    NOME VARCHAR(100),
    EMENTA VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS PRE_REQUISITOS (
    CURSO_A VARCHAR(10) PRIMARY KEY,
    CURSO_B VARCHAR(10) UNIQUE,
    CONSTRAINT FK_CURSO_A FOREIGN KEY (CURSO_A) REFERENCES CURSO(CODIGO) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_CURSO_B FOREIGN KEY (CURSO_B) REFERENCES CURSO(CODIGO) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS FORNECIMENTO_CURSO (
    FORNECIMENTO VARCHAR(6) NOT NULL,
    CURSO VARCHAR(10) NOT NULL,
    CONSTRAINT PK_FORNECIMENTO_CURSO PRIMARY KEY (FORNECIMENTO, CURSO),
    CONSTRAINT FK_FORNECIMENTO_CURSO FOREIGN KEY (FORNECIMENTO) REFERENCES FORNECIMENTO(PATROCINIO) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS PROJETO (
    TITULO VARCHAR(50) PRIMARY KEY,
    PROFESSOR VARCHAR(11) NOT NULL,
    ALUNO VARCHAR(11) NOT NULL,
    PUBLICO_ALVO VARCHAR(50),
    TEMA VARCHAR(100) NOT NULL,
    ESPECIFICACAO VARCHAR(100),
    CONSTRAINT SK_PROJETO UNIQUE(PROFESSOR, ALUNO),
    CONSTRAINT FK_ALUNO_PROJETO FOREIGN KEY (ALUNO) REFERENCES INDIGENA(CPF) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_PROJ_PROJETO FOREIGN KEY (PROFESSOR) REFERENCES PROFESSOR(FUNCIONARIO) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS PALAVRAS_CHAVE (
    PROJETO VARCHAR(50) NOT NULL,
    PALAVRA VARCHAR(50) NOT NULL,
    CONSTRAINT PK_PALAVRAS_CHAVE PRIMARY KEY (PROJETO, PALAVRA),
    CONSTRAINT FK_PALAVRAS_CHAVE FOREIGN KEY (PROJETO) REFERENCES PROJETO(TITULO) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS FORNECIMENTO_PROJETO (
    FORNECIMENTO VARCHAR(6) NOT NULL,
    PROJETO VARCHAR(50) NOT NULL,
    CONSTRAINT PK_FORNECIMENTO_PROJETO PRIMARY KEY (FORNECIMENTO, PROJETO),
    CONSTRAINT FK_FORNECIMENTO_FP FOREIGN KEY (FORNECIMENTO) REFERENCES FORNECIMENTO(PATROCINIO) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_PROJETO_FP FOREIGN KEY (PROJETO) REFERENCES PROJETO(TITULO) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS TURMA (
    ID SERIAL PRIMARY KEY, -- Usando serial para automaticamente gerar um id sintético
    CURSO VARCHAR(10) NOT NULL,
    ALDEIA VARCHAR(25) NOT NULL,
    ANO INTEGER NOT NULL CHECK(ANO <= EXTRACT(YEAR FROM CURRENT_DATE)), -- Ano mas salvo como string
    TRIMESTRE VARCHAR(2) NOT NULL, -- CHECK(TRIMESTRE = GET_CURRENT_TRIMESTER(ANO, TRIMESTRE)) AND CHECK (TRIMESTRE IN ('1o', '2o', '3o', '4o')); -- Usando o segundo check para casos onde o ano inserido não é o mesmo do atual, sendo assim é necessário fazer uma comparação para saber se o trimestre inserido está dentro dos valores válidos.
    HORARIO VARCHAR(5) CHECK(UPPER(HORARIO) IN ('MANHA', 'TARDE', 'NOITE')),
    PROFESSOR VARCHAR(11) NOT NULL,
    CONSTRAINT SK_TURMA UNIQUE(CURSO, ALDEIA, ANO, TRIMESTRE),
    CONSTRAINT FK_CURSO_TURMA FOREIGN KEY (CURSO) REFERENCES CURSO(CODIGO) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_CURSO_ALDEIA FOREIGN KEY (ALDEIA) REFERENCES ALDEIA("LOCAL") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_CURSO_PROF FOREIGN KEY (PROFESSOR) REFERENCES PROFESSOR(FUNCIONARIO) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS ALUNO_TURMA (
    ALUNO VARCHAR(11) NOT NULL, 
    TURMA SERIAL NOT NULL,
    APROVADO BOOLEAN,
    CONSTRAINT PK_ALUNO_TURMA PRIMARY KEY (ALUNO, TURMA),
    CONSTRAINT FK_ALUNO_AT FOREIGN KEY (ALUNO) REFERENCES INDIGENA(CPF) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_TURMA_AT FOREIGN KEY (TURMA) REFERENCES TURMA(ID) ON DELETE CASCADE ON UPDATE CASCADE
);